from dataclasses import dataclass


@dataclass(frozen=True)
class ApiParamNames:
  GROUP: str = 'grp'
  GENUS: str = 'gen'
  EPITHET: str = 'sp'
  SUBSPECIES: str = 'ssp'
  RECORDIST: str = 'rec'
  COUNTRY: str = 'cnt'
  LOCALITY: str = 'loc'
  REMARKS: str = 'rmk'
  ANIMAL_SEEN: str = 'animal-seen'
  PLAYBACK_USED: str = 'playback-used'
  LATITUDE: str = 'lat'
  LONGITUDE: str = 'lon'
  ALTITUDE: str = 'alt'
  BOX: str = 'box'
  BACKGROUND_SPECIES: str = 'also'
  SOUND_TYPE: str = 'type'
  OTHER_TYPE: str = 'othertype'
  SEX: str = 'sex'
  LIFE_STAGE: str = 'stage'
  RECORDING_METHOD: str = 'method'
  XC_ID: str = 'id'
  XC_NUMBER: str = 'nr'
  LICENSE: str = 'lic'
  XC_QUALITY: str = 'q'
  LENGTH: str = 'len'
  AREA: str = 'area'
  SINCE: str = 'since'
  YEAR: str = 'year'
  MONTH: str = 'month'
  COLLECTION_YEAR: str = 'colyear'
  COLLECTION_MONTH: str = 'colmonth'
  TEMP: str = 'temp'
  REG_NUMBER: str = 'regnr'
  AUTOMATIC: str = 'auto'
  DEVICE: str = 'dvc'
  MICROPHONE: str = 'mic'
  SAMPLE_RATE: str = 'smp'
  COMMON_NAME: str = 'en'
  UPLOAD_DATE: str = 'uploaded'
  RECORDED_DATE: str = 'date'
  RECORDED_TIME: str = 'time'
  PAGE_URL: str = 'url'
  FILE: str = 'file'
  FILE_NAME: str = 'file-name'
  SINCE: str = 'since'


# Instantiate to use as a namespace
aliases = ApiParamNames()
